name: Auto Commit and Push

on:
  schedule:
    - cron: "*/15 * * * *" # Cada 15 minutos

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Paso 1: Chequear el repositorio con historial completo
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Paso 2: Configurar Git
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Paso 3: Verificar todos los cambios, incluyendo archivos nuevos
      - name: Check for changes
        id: changes_check
        run: |
          # Añadir todos los archivos (incluso los nuevos) al área de staging
          git add -A
          
          # Verificar si hay cambios, incluyendo archivos nuevos
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected (including new files)."
            echo "CHANGES_EXIST=true" >> $GITHUB_ENV
            git status
          else
            echo "No changes to commit."
            echo "CHANGES_EXIST=false" >> $GITHUB_ENV
          fi

      # Paso 4: Commit y push si hay cambios
      - name: Commit and push changes
        if: env.CHANGES_EXIST == 'true'
        run: |
          git commit -m "Auto commit with changes $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main