name: Auto Commit and Push

# Disparar el workflow cada 15 minutos
on:
  schedule:
    - cron: "*/15 * * * *" # Cada 15 minutos

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Chequear el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Git
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Paso 3: Verificar si hay cambios para evitar commits vacíos
      - name: Check for changes
        id: changes_check
        run: |
          git status
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changes=true" >> $GITHUB_ENV
          fi

      # Paso 4: Commit y push (solo si hay cambios)
      - name: Commit and push changes
        if: env.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Obtener la fecha y el día para el mensaje del commit
          current_date=$(date "+%Y-%m-%d")
          current_day=$(date "+%A")
          git add .
          git commit -m "Commit made on ${current_day}, ${current_date}"
          git push origin main
